spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/f290DSM/configserverms.git
          search-paths: 'clients'
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always

server:
  port: 8888
